steps:
- bash: |
    az login --service-principal -u "$(ARMCLIENTID)" -p "$(ARMCLIENTSECRET)" --tenant "$(armtenantid)"
    az account set -s "$(armsubscriptionid)"
  displayName: Login to Azure
  workingDirectory: $(Build.Repository.LocalPath)/
- task: ShellScript@2
  inputs:
    scriptPath: $(Build.Repository.LocalPath)/scripts/aks-install-istio.sh
    args: "${{ parameters.workload }} ${{ parameters.stage }}"
  displayName: Install Istio