steps:
- script: terraform init -input=false -backend-config="container_name=${{ parameters.stage }}" -backend-config="access_key=$(ARMACCESSKEY)"
  workingDirectory: $(Build.Repository.LocalPath)/terraform/environment
  displayName: Terraform Init
- script: terraform validate -var-file=${{ parameters.varfile }} -var 'armsubscriptionid=$(armsubscriptionid)' -var 'armtenantid=$(armtenantid)' -var 'armclientid=$(ARMCLIENTID)' -var 'armclientsecret=$(ARMCLIENTSECRET)' -var 'armobjectid=$(ARMOBJECTID)'
  workingDirectory: $(Build.Repository.LocalPath)/terraform/environment
  displayName: Terraform Validate