steps:
- bash: |
    az login -u $(ARMCLIENTID) -p $(ARMCLIENTSECRET)
    az account set -s $(armsubscriptionid)
    az extension add --name resource-graph
    az graph query -q "Resources | where type =~ \"Microsoft.ContainerService/ManagedClusters\" | where properties.provisioningState =~ \"Succeeded\" | where tags[\"Environment\"] =~ \"$environment\" | where tags[\"Workload\"] =~ \"$workload\" | project name" -o yaml | awk '{ print $3 }' | xargs -I % sh -c "az aks get-credentials -g \"$workload-$environment-$module\" -n % ;"
    curl -L https://istio.io/downloadIstio | sh -
    cd istio-*
    export PATH=$PWD/bin:$PATH
    istioctl manifest apply
  displayName: Install Istio
  workingDirectory: $(Build.Repository.LocalPath)/helm/