steps:
- script: terraform init -input=false
  workingDirectory: $(Build.Repository.LocalPath)/terraform/environment
  displayName: Terraform Init
- script: terraform validate -var-file=${{ parameters.varfile }} -input=false -var 'armsubscriptionid=$(armsubscriptionid)' -var 'armtenantid=$(armtenantid)' -var 'armclientid=$(ARMCLIENTID)' -var 'armclientsecret=$(ARMCLIENTSECRET)' -var 'armobjectid=$(ARMOBJECTID)'
  workingDirectory: $(Build.Repository.LocalPath)/terraform/environment
  displayName: Terraform Validate