steps:
#- bash: |
#    az login -u $(ARMCLIENTID) -p $(ARMCLIENTSECRET)
#    az account set -s $(armsubscriptionid)
#    az extension add --name resource-graph
#    az graph query -q "Resources" \| where type =~ 'Microsoft.ContainerService/ManagedClusters' \| where tags['Environment'] =~ "$(parameters.stage)" \| where tags['Workload'] =~ "$(workload)" \| project "name" -o yaml \| awk '{ print $3 }' \| xargs -I % sh -c 'az aks update -g "$(parameters.stage)-$(workload)-$(parameters.module)" -n % --attach-acr "$(registry)";'
#  displayName: Enable ACR Integration
#  env:
#    registry: vmchooserregistry
#    workload: vmchooser
- task: ShellScript@2
  inputs:
    scriptPath: $(Build.Repository.LocalPath)/scripts/aks-configure-acr-integration.sh
    args: "$(ARMCLIENTID) $(ARMCLIENTSECRET) $(armsubscriptionid) ${{ parameters.module }} ${{ parameters.stage }} ${{ parameters.workload }} ${{ parameters.registry }}"