steps:
- script: terraform init -input=false -backend-config="container_name=${{ parameters.stage }}" -backend-config="access_key=$(storageaccountkey)" -backend-config="subscription_id=$(armsubscriptionid)" -backend-config="storage_account_name=$(storageaccountname)"
  workingDirectory: $(Build.Repository.LocalPath)/terraform/${{ parameters.module }}
  displayName: Terraform Init
- task: AzureCLI@2
  displayName: Azure CLI Test
  inputs:
    azureSubscription: ame of the Azure subscription><N
    scriptType: shell
    scriptLocation: inlineScript
    inlineScript: |
        az --version
        az account show
        az account set --subscription $(armsubscriptionid)
- script: terraform plan -input=false -var-file=${{ parameters.varfile }} -var 'subscription_id=$(armsubscriptionid)' -var 'tenant_id=$(armtenantid)' -var "prefix=${{ parameters.stage }}"
  workingDirectory: $(Build.Repository.LocalPath)/terraform/${{ parameters.module }}
  displayName: Terraform Plan
- script: terraform apply -input=false -auto-approve -var-file=${{ parameters.varfile }} -var 'subscription_id=$(armsubscriptionid)' -var 'tenant_id=$(armtenantid)' -var "prefix=${{ parameters.stage }}"
  workingDirectory: $(Build.Repository.LocalPath)/terraform/${{ parameters.module }}
  displayName: Terraform Apply