steps:
- script: terraform init -backend=false
  workingDirectory: $(Build.Repository.LocalPath)/terraform/${{ parameters.module }}
  displayName: Terraform Init
- script: terraform validate
  workingDirectory: $(Build.Repository.LocalPath)/terraform/${{ parameters.module }}
  displayName: Terraform Validate
- publish: $(Build.Repository.LocalPath)
  artifact: VMchooserLandscape${{ parameters.module }}