name: $(Date:yyyyMMdd).$(Rev:.r)
resources:
  repositories:
  - repository: vmchooserlandscaping
    type: git
    name: vmchooser/landscaping
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /terraform/
    - /.pipelines/templates/tf*
jobs:
- job: LandScaping_Build_Dev
  variables:
  - group: vmchooserdevsp
  pool:
    name: Default
  steps:
  - template: ../templates/tf-environment-build.yml
    parameters:
      varfile: dev.tfvars
- job: LandScaping_Deploy_Dev
  variables:
  - group: vmchooserdevsp
  dependsOn: LandScaping_Build_Dev
  pool:
    name: Default
  steps:
  - template: ../templates/tf-environment-deploy.yml
    parameters:
      varfile: dev.tfvars