name: $(Date:yyyyMMdd).$(Rev:.r)
resources:
  repositories:
  - repository: vmchooserlandscaping
    type: github
    name: vmchooser/landscaping
    endpoint: vmchooser
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /terraform/
    - /.pipelines/templates/tf*
stages:
- stage: Dev
  displayName: Build stage
  jobs:
  - job: LandScaping_Build_Dev
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-build.yml
      parameters:
        varfile: dev.tfvars
        stage: dev
- stage: DeployDev
  displayName: Deploy Dev Environment
  dependsOn: Dev
  jobs:
  - job: LandScaping_Deploy_Shared_Core
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-deploy.yml
      parameters:
        varfile: ../environments/shared.tfvars
        stage: shared
        module: shared
  - job: LandScaping_Deploy_Dev_Core
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-deploy.yml
      parameters:
        varfile: ../environments/dev.tfvars
        stage: dev
        module: core
  - job: LandScaping_Deploy_Dev_Aks
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ../templates/tf-environment-deploy.yml
      parameters:
        varfile: ../environments/dev.tfvars
        stage: dev
        module: aks